version: '3.8'


services:

  backend:

    image: vitbackend-app

    build: .

    container_name: vitbackend-app

    ports:

      - "8080:8080"

    environment:

      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/vitg

      - SPRING_DATASOURCE_USERNAME=root

      - SPRING_DATASOURCE_PASSWORD=1234

    depends_on:

      - db


  db:

    image: mysql:8

    container_name: vitg-db

    environment:

      - MYSQL_ROOT_PASSWORD=1234

      - MYSQL_DATABASE=vitg

    ports:

      - "3306:3306"

